driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero

verifier:
  name: pester

platforms:
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard
suites:
  - name: autorun
    run_list:
      - recipe[test::autorun]
  - name: certificate
    run_list:
      - recipe[test::certificate]
  - name: feature
    run_list:
      - recipe[test::feature]
  - name: font
    run_list:
      - recipe[test::font]
  - name: http_acl
    run_list:
      - recipe[test::http_acl]
  - name: package
    run_list:
      - recipe[test::package]
  - name: path
    run_list:
      - recipe[test::path]
  - name: tasks
    run_list:
      - recipe[test::tasks]
